version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_DB:${DB_NAME}
      - POSTGRES_PASSWORD:${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
